replicaCount: 3

image:
  repository: us-central1-docker.pkg.dev/terraform-project-mishanyag/artemis/artemis@sha256:8c4738c8e63b0a05ff7d95f18052950fc4ec39fd05fcfd287607fd7f24b76359
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "9.0.0"

service:
  type: ClusterIP
  port: 50000

ingress:
  enabled: true
  className: "nginx"
  annotations:     
    ingress.kubernetes.io/ssl-redirect: "false"
    # kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns01
    acme.cert-manager.io/http01-edit-in-place: "true"
  hosts:
    - host: artemis-qa.mg-aws.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: 
    - secretName: artemis-tls
      hosts:
        - artemis-qa.mg-aws.com